### ISSUE TITLE
espressioni booleane e operatori logici

### ISSUE THREAD

**Issue by FabioZTessitore** [Edivad1234/helloword#10]
## Espressioni booleane

Le espressioni booleane sono quelle espressioni
che restituiscono solo valore Vero (True) o Falso (False).

Si ottengono mediante l'uso degli operatori:

`==`    uguale

`<`     minore

`>`     maggiore

`<=`    minore o uguale

`>=`    maggiore o uguale

`!=`    diverso

Es. dopo aver lanciato l'interprete Python
prova ad eseguire questi comandi:

```py
>>> 3 == 3
True

>>> 3 < 1
False

>>> 5 != 7
True

>>> 5 <= 7
True
```

## Operatori logici

Gli operatori logici (and, or, not) permettono di combinare espressioni booleane

```py
>>> 3 <= 3 and 7 > 9
False # solo la prima e' Vera

>>> 3 <= 3 or 7 > 9
True # almeno la prima e' Vera

>>> not 10 < 7
True # 10 < 7 e' False
```

**Comment by Edivad1234** [comment]
Tutto chiaro anche sulle espressioni booleane e operatori logici
