### ISSUE TITLE
volume

### ISSUE THREAD

**Issue by FabioZTessitore** [Edivad1234/helloword#13]
Scrivi un programma che calcoli il volume di un cubo o di una sfera
in base ad una scelta effettuata dall'utente.
Se l'utente sceglie di calcolare il volume di un cubo,
il programma chiedera' l'input del relativo lato,
altrimenti chiedera' il raggio della sfera.

Esempio di esecuzione:
```bash
Calcolo del volume di un cubo o di una sfera
Effettua una scelta (1 - Cubo, 2 - Sfera)
? 1
Lato del cubo: 2
Il cubo di lato 2 ha volume 8

**Comment by Edivad1234** [comment]
Prof ho fatto il programma del cubo e della sfera. L'ho caricato, si chiama
cuboesfera.py

2016-11-23 16:55 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
va bene, però dai un'occhiata alla mia versione (volume.py)
anche se fanno la stessa cosa il mio dovrebbe essere più chiaro (nomi delle variabili, casi dell'if, qualche commento iniziale)

ricorda che il programma lo scrivi una volta e lo leggi mille volte e quindi deve essere chiaro

**Comment by Edivad1234** [comment]
Ho visto, in effetti il mio programma non è molto chiaro. Volete che cambio
anche io i nomi alle variabili  e aggiungo qualche commento? O lo rimango
così?

Il giorno 23 novembre 2016 17:54, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
no, era solo per esempio
sui prossimi fai più attenzione

**Comment by Edivad1234** [comment]
Va bene!

2016-11-23 18:01 GMT+01:00 Fabio Z Tessitore notifications@github.com:
