### ISSUE TITLE
primo grado

### ISSUE THREAD

**Issue by FabioZTessitore** [Edivad1234/helloword#14]
Scrivi un programma che trovi la soluzione a equazioni di primo grado
nella forma ax+b=0, con a e b interi.

Il programma dovrebbe tener conto dei casi particolari: a, b o entrambi nulli.

**Comment by Edivad1234** [comment]
Prof. io ho caricato il programma, si chiama eqprimogrado.py, l'ho fatto in
questo modo ma non so se va bene

2016-11-23 16:55 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
ma non da nessun risultato?

**Comment by Edivad1234** [comment]
Si a me li da, adesso però lo sto modificando appena lo finisco ve lo mando
aggiornato

2016-11-23 19:10 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
hai fatto una cosa tipo Vessella

**Comment by Edivad1234** [comment]
Professore scusate ma sto avendo alcuni problemi. Ho caricato il programma
ma mi da un problema di sintassi

2016-11-23 19:15 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
forse alla riga 17 volevi mettere if

in ogni caso ci sono troppi if (ne bastano 3)

**Comment by Edivad1234** [comment]
Professore ho provato a correggere, ci ho messo 3 if. Vedete se va bene

Il giorno 23 novembre 2016 19:43, Fabio Z Tessitore <
notifications@github.com> ha scritto:

**Comment by FabioZTessitore** [comment]
Sig. Antonucci, lei non sa niente di matematica

**Comment by Edivad1234** [comment]
Prof. a matematica sono abbastanza bravo ahahaha.. Il problema è questo programma l'ho fatto di fretta e quindi non ho controllato volta in volta ahaha. Domani ricontrollo e vedo i miei errori. Buonanotte, a domani!
