### ISSUE TITLE
secondo grado

### ISSUE THREAD

**Issue by FabioZTessitore** [Edivad1234/helloword#15]
Scrivi un programma che trovi le soluzioni a equazioni di secondo grado
nella forma ax^2+bx+c=0, con a, b e c interi.
Il programma dovrebbe tener conto dei casi particolari.

Per il calcolo della radice quadrata si puo' utilizzare la funzione `sqrt()`
della libreria matematica math
```python
import math

... math.sqrt() ...
```

**Comment by FabioZTessitore** [comment]
bisogno di aiuto?

**Comment by FabioZTessitore** [comment]
devi correggere le soluzioni, mancano le parentesi

**Comment by FabioZTessitore** [comment]
le parentesi, le parentesi

**Comment by FabioZTessitore** [comment]
la facciamo questa correzione?

**Comment by FabioZTessitore** [comment]
continuiamo?

**Comment by Edivad1234** [comment]
Prof. buongiorono, ho finito con il python, possiamo passare al nuovo
argomento?

2017-01-13 14:57 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
certo, c'è l'introduzione al C

**Comment by Edivad1234** [comment]
Non riesco a trovarla!

**Comment by FabioZTessitore** [comment]
Dove?

Il 27 gen 2017 4:42 PM, "Edivad1234" <notifications@github.com> ha scritto:
