### ISSUE TITLE
cubo

### ISSUE THREAD

**Issue by FabioZTessitore** [Edivad1234/helloword#7]
Creare un programma cubo.py che chieda all'utente
il lato di un cubo (intero) e ne stampi il volume

**Comment by FabioZTessitore** [comment]
non va

**Comment by FabioZTessitore** [comment]
non va bene

**Comment by FabioZTessitore** [comment]
questo non lo hai cambiato?

**Comment by Edivad1234** [comment]
Ah si scusate, ho caricato solo sfera.py. cubo.py l'ho cambiato, ma ho dimenticato di caricarlo aggiornato
