### ISSUE TITLE
sfera

### ISSUE THREAD

**Issue by FabioZTessitore** [Edivad1234/helloword#8]
Creare un programma sfera.py che chieda all'utente
il raggio di una sfera (intero) e ne stampi superficie e volume

Note:
Per portare a termine il compito e'
necessaria la costante matematica pi greco.
Si puo' definire una variabile assegnandole tale valore:
```python
pi = 3.141592654
```
Oppure si puo' utilizzare quella gia'
definita nella libreria matematica:
```python
import math

...

math.pi

...
```

**Comment by Edivad1234** [comment]
Prof. ho fatto i due programmi cubo.py e sfera.py. Dovrebbero essere giuste
anche le formule ahah

2016-11-21 20:33 GMT+01:00 Fabio Z Tessitore notifications@github.com:

**Comment by FabioZTessitore** [comment]
prova a usare math.pi e attento alle formule
