### ISSUE TITLE
L'operatore modulo

### ISSUE THREAD

**Issue by FabioZTessitore** [Edivad1234/helloword#9]
L'operatore modulo

Oltre alle classiche quattro operazioni
tutti i linguaggi di programmazione
mettono a disposizione una quinta operazione:
il modulo (o resto della divisione)

Apri l'interprete Python
```sh
$ python
```

e prova ad eseguire questi comandi
```py
>>> 7 % 4
3
```

```
>>> 10 % 2
0
```

**Comment by Edivad1234** [comment]
Prof tutto chiaro sui moduli
